### ISSUE TITLE
Request : Undo Option / Restore removed player with epgp

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#16] opened 2015-02-26 20:53 UTC
Accidentally removed some selected Member. Clicked Undo Last Action.
Member have been restored but without EP/GP and Logs

**Comment by Drutol** [comment] 2015-02-27 12:42
Hmm it restores removed players with all their things...

**Comment by Hysteriana** [comment] 2015-02-27 15:19
just tried with only 2 selected, and it worked.

last time i had the whole raid selected, 19 ppl, clicked on remove, but only 6 or so had been removed.
when i clicked restored, those 6 where restored blank just with default start ep/gp.

will test it again as soon as the export / import is working :)

**Comment by Drutol** [comment] 2015-02-27 15:21
Oh okay , now I may know where the issue is.

**Comment by Drutol** [comment] 2015-02-27 15:30
Fixed in rev 130.

**Closed as completed by Drutol** 2015-02-27 15:30 UTC
Labels: Bug
