### ISSUE TITLE
Error on login / ReloadUI after game restart with timed awards active

### ISSUE THREAD

**Issue by ElmRR** [Mordonus/RaidOps#311] opened 2015-07-22 22:09 UTC
Hi,

I'm seeing this error after relogging with timed awards still active. Upon logging back in RaidOps would throw this up as soon as the UI tried to load even when completely restarting the game:

...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:792: attempt to index field 'wndActivity' (a nil value)
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:792: in function 'UndoPopulate'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:677: in function 'UndoAddActivity'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:2003: in function 'TimeAwardAward'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:1904: in function 'TimeAwardStart'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:1932: in function 'TimeAwardRestore'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:485: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:327>

**Comment by Drutol** [comment] 2015-07-23 05:30
I believe that this is caused by 'Saved timed award undo' , You can disable this as a temporary solution before I make v2.27 stable and usable.

**Comment by ElmRR** [comment] 2015-07-23 12:44
Thanks for the advice - will give this a go tonight.

Thanks for all the hard work, support and quick responses as well :)

**Comment by Drutol** [comment] 2015-07-23 12:49
You can also add this line to DKP.lua after line 791.

> if not self.wndActivity then return end

It should look like this:

```
function DKP:UndoPopulate()
    if not self.wndActivity then return end
    local grid = self.wndActivity:FindChild("Grid")
    grid:DeleteAll()
    for k,activity in ipairs(tUndoActions) do
        grid:AddRow(k)
        grid:SetCellData(k,1,k)

```

**Comment by Hysteriana** [comment] 2015-07-23 21:06
cant confirm, did several reloadui while time award timer running, no problems at all

**Comment by Drutol** [comment] 2015-07-24 04:50
This is fairly rare issue , timer has been saved exactly when it was going to reset. Timed award module is initialized before undo module , I just need to adjust this init order.

**Comment by Drutol** [comment] 2015-07-30 18:30
Fixed in v2.27

**Closed as completed by Drutol** 2015-07-30 18:30 UTC
